# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f672430c21a8f4b4064541573d3aca1e6407487704c08a4a48135d05da45d0be9aeef17d022fca905b9ee06509d75d356268da15d3eed077fc5e0e516fd02b2b

test:
  secret_key_base: 1b407cea5766eed31edd8fb67c35de03913a55887904fdea89fc1223f710c3d83141664494014a81f75217a0be56e25d857a5e18461ef7bec61bd87325228dbc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
